### ISSUE TITLE
spiflash.c wait_for_device_ready never returns on KC705

### ISSUE THREAD

**Issue by sbourdeauducq** [m-labs/misoc#11]
This makes most flash functions unusable.

**Comment by fallen** [comment]
If you print the status register value (sr) from within the while loop in wait_for_device_ready, what value is it?

**Comment by sbourdeauducq** [comment]
0xff

**Comment by fallen** [comment]
Could you try changing this line https://github.com/m-labs/misoc/blob/master/misoclib/mem/flash/spiflash.py#L88 to read
`self.miso.status.eq(dq.i[1])`
instead of
`self.miso.status.eq(dq.i[-1])`
?

I think the issue is my code didn't handle well the case where the dq pad is of width > 2, and on kc705 the dq length is 4.

**Comment by sbourdeauducq** [comment]
Works.
