### ISSUE TITLE
DDR3 broken on some Sayma boards

### ISSUE THREAD

**Issue by sbourdeauducq** [m-labs/misoc#63]
https://github.com/m-labs/sinara/issues/382#issuecomment-349025235

**Comment by gkasprow** [comment]
I have Vivado test designs that I used to verify DDR3 operation.
Both memory banks tests were successful.
Is there something wrong in HW?
On some boards there was not mounted R105resistor that may cause memory controller failure during initialisation. It was reported [here](https://github.com/m-labs/sinara/issues/209#issuecomment-332620991)
This may cause an issue only with DDR2 controller. But Xilinx core worked fine since this sets impedance reference only on SDRAM control lines which do not need to calibrate its impedance.

**Comment by enjoy-digital** [comment]
@gkasprow: this is not related to HW but to our PHY. I think this is now fixed and we will close this when validated on all sayma amc.

**Comment by jbqubit** [comment]
I am compiling .bit from master now and will report if it works.

**Comment by jbqubit** [comment]
Confirmed that Memtest passes on my Sayma_AMC using .bit built from master.

**Comment by sbourdeauducq** [comment]
Also still works on sayma1 and sayma2 at m-labs. @enjoy-digital thanks for the rapid resolution.
